engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
ratings:
  paths:
  - app/**
  - "**.rb"
exclude_paths:
- "**/vendor/**/*"
