version: '2'
services:
  bundle:
    image: busybox
    volumes:
      - /root/bundle
  app:
    tty: true
    stdin_open: true
    build: .
    environment:
      - "RAILS_ENV=development"
      - "BUNDLE_PATH=/root/bundle"
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - './:/root/uprogress'
    volumes_from:
      - bundle

  db:
    image: postgres:9.4.5
    ports:
      - "5432"
    volumes:
      - postgres:/var/lib/postgres
volumes:
  postgres:
