version: '2'
services:
  app:
    tty: true
    stdin_open: true
    build: .
    environment:
      RAILS_ENV: 'development'
    volumes:
      - './:/var/www/docker_example'

    links:
      - db

    ports:
      - "3000:3000"

  db:
    image: postgres:9.4.5
    ports:
      - "5432"
    volumes:
      - postgres:/var/lib/postgres
volumes:
  postgres:
