version: '2'
services:
  app:
    image: vsokoltsov/uprogress
    build: .
    command: bash -l -c '/var/www/docker_example/config/docker/run_server.sh'
    env_file:
      - /root/.env.production

    links:
      - db

    ports:
      - "80:3000"

  db:
    image: postgres:9.4.5
    ports:
      - "5432"
    volumes:
      - postgres:/var/lib/postgres
volumes:
  postgres:
