app:
  tty: true
  stdin_open: true
  build: .
  env_file: .env
  environment:
    RAILS_ENV: $RAILS_ENV

  links:
    - db
  volumes:
    - './:/var/www/docker_example'

  ports:
    - "3000:3000"

db:
  image: postgres:9.4.5
  ports:
    - "5432"
  volumes:
    - docker-example-postgres:/var/lib/postgresql/data
