default: &default
  adapter: postgresql
  host: db
  encoding: unicode
  pool: 5
  username: postgres

development:
  <<: *default
  database: uprogress_development

test:
  <<: *default
  database: uprogress_test

production:
  <<: *default
  database: uprogress_production
