default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: uprogress_development

test:
  <<: *default
  database: uprogress_test

production:
  <<: *default
  database: uprogress_production
